agents:
  - id: 0
    type: "student"
    schedule:
      arriving: "07:30:00"
      leaving: "13:30:00"
    style: "smart"
    behaviour: "active"
    mask: "n95"
    vaccine: "pfizer/moderna"

  - id: 3
    type: "student"
    schedule:
      arriving: "07:55:00"
      leaving: "13:55:00"
    style: "smart"
    behaviour: "active"
    mask: "n95"
    vaccine: "no-vax"

  - id: 5
    type: "student"
    schedule:
      arriving: "07:40:00"
      leaving: "13:50:00"
    style: "smart"
    behaviour: "quiet"
    mask: "surgical"
    vaccine: "astra-zeneca"

  - id: 8
    type: "student"
    schedule:
      arriving: "07:50:00"
      leaving: "13:55:00"
    style: "smart"
    behaviour: "active"
    mask: "surgical"
    vaccine: "any"

  - id: 10
    type: "student"
    schedule:
      arriving: "07:40:00"
      leaving: "13:45:00"
    style: "smart"
    behaviour: "quiet"
    mask: "n95"
    vaccine: "astra-zeneca"

  - id: 14
    type: "student"
    schedule:
      arriving: "07:45:00"
      leaving: "13:40:00"
    style: "smart"
    behaviour: "active"
    mask: "surgical"
    vaccine: "pfizer/moderna"

  - id: 15
    type: "student"
    schedule:
      arriving: "07:48:00"
      leaving: "13:52:00"
    style: "smart"
    behaviour: "active"
    mask: "cloth"
    vaccine: "any"

  - id: 17
    type: "student"
    schedule:
      arriving: "07:50:00"
      leaving: "13:50:00"
    style: "smart"
    behaviour: "quiet"
    mask: "n95"
    vaccine: "any"

  - id: 20
    type: "student"
    schedule:
      arriving: "07:45:00"
      leaving: "13:40:00"
    style: "smart"
    behaviour: "quiet"
    mask: "surgical"
    vaccine: "pfizer/moderna"

  - id: 23
    type: "student"
    schedule:
      arriving: "07:35:00"
      leaving: "13:45:00"
    style: "smart"
    behaviour: "active"
    mask: "cloth"
    vaccine: "astra-zeneca"

  - id: -1
    type: "teacher"
    schedule:
      arriving: "07:55:00"
      leaving: "13:45:00"
    style: "smart"
    behaviour: "quiet"
    mask: "n95"
    vaccine: "any"