agents:
  - id: 0
    type: "student"
    schedule:
      arriving: "07:50:00"
      leaving: "13:50:00"
    style: "smart"
    behaviour: "quiet"
    mask: "n95"
    vaccine: "any"
  - id: 0
    type: "teacher"
    behaviour: "quiet"