placeables:
  - type: Environment
    points: [[1, 1], [1, 11], [20, 11], [20, 1]]
    color: [240, 240, 240]
    geometry: polygon

  - type: Table
    x: 5
    y: 2
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 4
    y: 2
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 4
    y: 3
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 8
    y: 2
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 7
    y: 2
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 7
    y: 3
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 11
    y: 2
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 10
    y: 2
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 10
    y: 3
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 14
    y: 2
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 13
    y: 2
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 13
    y: 3
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 5
    y: 5
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 4
    y: 5
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 4
    y: 6
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 8
    y: 5
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 7
    y: 5
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 7
    y: 6
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 11
    y: 5
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 10
    y: 5
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 10
    y: 6
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 14
    y: 5
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 13
    y: 5
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 13
    y: 6
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 5
    y: 8
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 4
    y: 8
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 4
    y: 9
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 8
    y: 8
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 7
    y: 8
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 7
    y: 9
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 11
    y: 8
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 10
    y: 8
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 10
    y: 9
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 14
    y: 8
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 13
    y: 8
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 13
    y: 9
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 5
    y: 8
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 4
    y: 8
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 4
    y: 9
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 8
    y: 8
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 7
    y: 8
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 7
    y: 9
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 11
    y: 8
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 10
    y: 8
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 10
    y: 9
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 14
    y: 8
    width: 1
    height: 2
    color: [105, 105, 105]
    collision: True
    geometry: rectangle

  - type: Chair
    x: 13
    y: 8
    color: [0, 102, 204]
    geometry: circle

  - type: Chair
    x: 13
    y: 9
    color: [0, 102, 204]
    geometry: circle

  - type: Table
    x: 17
    y: 8
    width: 1
    height: 2
    color: [75, 75, 75]
    collision: True
    geometry: rectangle

  - type: Armchair
    x: 18
    y: 8
    color: [0, 102, 204]
    geometry: circle

  - type: Entrance
    x: 1
    y: 11
    width: 2
    height: 1
    color: [255, 255, 50]
    geometry: rectangle

  - type: WhiteBoard
    x: 19
    y: 2
    width: 1
    height: 4
    color: [64, 64, 64]
    collision: True
    geometry: rectangle

  - type: BackHotspot
    x: 1
    y: 2
    width: 1
    height: 5
    color: [0, 204, 102]
    geometry: rectangle

  - type: FrontHotspot
    x: 18
    y: 2
    width: 1
    height: 4
    color: [0, 204, 102]
    geometry: rectangle
